In [21]:
import numpy as np
import matplotlib.pyplot as plt
import os
import open3d as o3d
from PIL import Image


def get_cuboid_mesh(verts, elems, values, cmap="jet"):
    
    tri_idx = np.array([[0,0,0,0,0,0,6,6,6,6,6,6],
                        [2,3,7,4,1,5,2,3,1,5,4,7],
                        [1,2,3,7,5,4,3,7,2,1,5,4]], dtype=int)
    mesh = o3d.geometry.TriangleMesh()
    tris = np.zeros([12*elems.shape[0],3], dtype=int)
    for i, elem in enumerate(elems):
        tris[i*12:(i+1)*12,:] = elem[tri_idx].T-1
    
    mesh.vertices = o3d.utility.Vector3dVector(verts)
    mesh.triangles = o3d.utility.Vector3iVector(tris)

    cmap = plt.get_cmap(cmap)
    lb, ub = min(values), max(values)
    values = (values - lb) / (ub - lb)
    mesh.vertex_colors = o3d.utility.Vector3dVector(cmap(values)[:,:3])
    return mesh
                          
data_path = r"C:\Users\XuanLiang\Documents\Netfabb_Fusion360_data\TEST\\data\bazinga\\"
size = os.listdir(data_path)
data_files = os.listdir(data_path)

In [22]:
for i in range(len(size)):
    directory = r"C:\Users\XuanLiang\Documents\Netfabb_Fusion360_data\TEST\data\bloop"
    data = np.load(data_path + data_files[i])
    print(data)
    verts, elems, disp = data["verts"], data["elems"], data["disp"]
    mesh = get_cuboid_mesh(verts, elems, disp[:,2])
    def rotate_shape():
        rotation_angle = -np.pi / 4
        rotation_matrix = np.array([[np.cos(rotation_angle), -np.sin(rotation_angle), 0],
                                    [np.sin(rotation_angle), np.cos(rotation_angle), 0],
                                    [0, 0, 1]])
        rotation_matrix_x = np.array([[1, 0, 0],
                                        [0, np.cos(rotation_angle), -np.sin(rotation_angle)],
                                        [0, np.sin(rotation_angle), np.cos(rotation_angle)]])
        mesh.rotate(rotation_matrix, center=mesh.get_center())
        mesh.rotate(rotation_matrix_x, center=mesh.get_center())

    def modify_FOV(vis):
        screenshot = vis.capture_screen_float_buffer(False)
        # Convert the NumPy array to an image
        img = Image.fromarray((np.asarray(screenshot) * 255).astype('uint8'), 'RGB')
        filepath = os.path.join(directory, f'part{i}_position{j}.jpg')
        img.save(filepath)
        vis.destroy_window()
    for j in range(6):
        vis = o3d.visualization.Visualizer()
        vis.create_window()
        vis.add_geometry(mesh)
        rotate_shape()
        vis.register_animation_callback(modify_FOV)

        vis.run()
        vis.destroy_window()

NpzFile 'C:\\Users\\XuanLiang\\Documents\\Netfabb_Fusion360_data\\TEST\\\\data\\bazinga\\\\data2.npz' with keys: verts, elems, disp


In [8]:
data = np.load(data_path + data_files[1])
print("Arrays in the .npz file:")
for key in data.files:
    print(key)

# Access and print the data of each array
for key in data.files:
    print(f'Data in array {key}:')
    print(data[key])
    print(len(data[key]))

Arrays in the .npz file:
verts
elems
disp
Data in array verts:
[[-16.875    -11.25      10.08    ]
 [-15.75     -11.25      10.08    ]
 [-15.75     -10.3125    10.08    ]
 ...
 [ 21.375     11.015625 104.4     ]
 [ 21.375     11.015625 104.76    ]
 [ 21.375     11.25     104.76    ]]
97063
Data in array elems:
[[    1     2     3 ...     6     7     8]
 [    4     3     9 ...     7    11    12]
 [   10     9    13 ...    11    15    16]
 ...
 [96988 97058 95078 ... 97059 97060 96997]
 [96996 95078 97061 ... 97060 97062 97004]
 [97002 97061 95079 ... 97062 97063 97011]]
51605
Data in array disp:
[[ 0.15200213  0.10025723  0.42456964]
 [ 0.14338128  0.10125281  0.36106658]
 [ 0.1427376   0.09187573  0.33493212]
 ...
 [-0.1701286  -0.09290852  0.1311009 ]
 [-0.16568182 -0.09162588  0.12452719]
 [-0.16637708 -0.09334102  0.1288468 ]]
97063


In [15]:
data = np.load(data_path + data_files[0])
print("Arrays in the .npz file:")
for key in data.files:
    print(key)

# Access and print the data of each array
for key in data.files:
    print(f'Data in array {key}:')
    print(data[key])
    print(len(data[key]))

Arrays in the .npz file:
verts
elems
disp
Data in array verts:
[[-0.045       0.018       0.        ]
 [-0.045       0.018      -0.075     ]
 [-0.045       0.018      -0.00220588]
 ...
 [-0.0223435   0.01575    -0.02428369]
 [-0.02055897  0.01575    -0.02536764]
 [-0.02740464  0.01575    -0.06472893]]
13852
Data in array elems:
[[    1     1     1 ...   220  3724  3299]
 [    1     1     1 ... 13815 13814   220]
 [    1     1     1 ...  3736   145   220]
 ...
 [    1     1     1 ...  7001  4583  4584]
 [    1     1     1 ...  6200  4586  6199]
 [    1     1     1 ...  9124  7561  8875]]
8922
Data in array disp:
[[ 0.15793965  0.02658368  0.0141346 ]
 [ 0.16234086  0.02938625 -0.01466824]
 [ 0.18974092  0.01660428  0.01137512]
 ...
 [-0.00168372 -0.09989102  0.00542101]
 [-0.02141701 -0.09717987  0.00499071]
 [ 0.04677798 -0.09350707 -0.01155528]]
13852
